### ISSUE TITLE
IOS发送语音按钮效果

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#106]
- 按钮变化放大效果可以相对现有比例增加100%
- 按钮点击应立即展现效果，不应该延时
- 语音长度在结束录音前后长度不一致
- 当上一条信息发送成功时，当前录制的语音动画会闪动

**Comment by isaak-zmg** [comment]
语音录制过程中 点击返回按钮 录音按钮就会一直闪动
