### ISSUE TITLE
语音需占用音频通道

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#157]
- 在后台使用应用时也可以继续滚动播放当前房间的语音
- 在播放过程中，收到新的语音也需要播放

**Comment by qaqaqa** [comment]
@isaak-zmg 已完成

**Comment by qaqaqa** [comment]
@isaak-zmg 已完成

**Comment by houyidg** [comment]
@isaak-zmg 已完成

**Comment by isaak-zmg** [comment]
@zhuxiaogit  连续播放 播放到已读消息就停止 不用跳过已读继续播放未读
