### ISSUE TITLE
语音重试发送功能

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#167]
- 未发送的语音放入待发送队列
- 界面将语音闪烁表示未未发送成功的语音
- 一旦有网络将尝试重发语音？（重发机制需讨论）

**Comment by qaqaqa** [comment]
@isaak-zmg 已完成

**Comment by qaqaqa** [comment]
@isaak-zmg 已完成

**Comment by houyidg** [comment]
@isaak-zmg 已完成

**Comment by isaak-zmg** [comment]
@zhuxiaogit 预发送消息不用闪烁 闪烁时头像不能闪烁（参考IOS） 闪烁间隔0.5S

**Comment by houyidg** [comment]
@isaak-zmg 已完成
