### ISSUE TITLE
基础项目结构搭建（Android）

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#180]
### 配置
- 应用程序配置管理

### 验证
- 表单数据验证
- 实体对象数据格式验证

### 网络
- websocket通信（signalr）
- http基础操作（webapi）

### 仓储（repository）
- 持久化数据抽象
- 缓存数据抽象
- 文件管理抽象

### 工具
- 字符串序列化（json）
- 字符串基础操作

### 消息
- 可订阅发布的消息总线（跨线程通信，异步操作，解耦方法）

### 表达式
- 数据过滤规则

Remark: 预计4天，2017-05-26 完成

**Comment by ffantasy** [comment]
- 缺少数据验证组件
- 缺少数据过滤规则
- signalr 通信部分代码需要优化

**Comment by ffantasy** [comment]
已完成。
