### ISSUE TITLE
添加邮件导入票类流程

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#188]
![image](https://user-images.githubusercontent.com/3402605/26864449-c64f95b8-4b8a-11e7-8bfe-23e34f97e847.png)
![image](https://user-images.githubusercontent.com/3402605/26864450-c9f894c6-4b8a-11e7-8d41-1e37106ae13e.png)

**Comment by qaqaqa** [comment]
@isaak-zmg 已完成

**Comment by houyidg** [comment]
@isaak-zmg 已完成

**Comment by isaak-zmg** [comment]
android 导入的票的活动不能接收消息
