### ISSUE TITLE
录音提示信息

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#189]
- 进入房间时显示录音提示信息
- 5秒后提示信息消失（渐变消失） 
- 点击提示信息或第一条语音该提示信息应消失
![image](https://cloud.githubusercontent.com/assets/3402605/26386785/724fe112-407b-11e7-9643-220bbc065435.png)

**Comment by qaqaqa** [comment]
@isaak-zmg 已完成

**Comment by houyidg** [comment]
@isaak-zmg 已完成

**Comment by isaak-zmg** [comment]
已测
