### ISSUE TITLE
IOS聊天语音过长时，显示长度不正确

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#20]
IOS聊天语音过长时，显示长度不正确

![image](https://cloud.githubusercontent.com/assets/3402605/21300931/8583d8dc-c5e3-11e6-8f25-13b16c8ad581.png)

> device: iphone 6 plus
platform: ios 10.2.0

**Comment by qaqaqa** [comment]
@Caskia

**Comment by isaak-zmg** [comment]
语言超过40秒 发送失败 后续发送也会失败
