### ISSUE TITLE
Android  与IOS功能不一致

### ISSUE THREAD

**Issue by deng-yc** [SparxoOpenSource/Glood-ReactNative#27]
![image](https://cloud.githubusercontent.com/assets/12589538/21300989/3489b4a0-c5e4-11e6-8e6c-8da5d0f52179.png)
1.图中圈的按钮与ios不一致
> device: HUAWEI H30-U10
platform: MIUI 8

**Comment by isaak-zmg** [comment]
android ios 活动列表title不一致 @zhuxiaogit @qaqaqa

**Comment by houyidg** [comment]
close
