### ISSUE TITLE
IOS，Android 扫描二维码与效果图不一直

### ISSUE THREAD

**Issue by deng-yc** [SparxoOpenSource/Glood-ReactNative#36]
ios 关闭按钮是×，效果图是←    参考 #13
> iphone 5s ,ios 10.2

安卓，关闭按钮是 < 效果图是←，方框是长方形，效果图是带圆角的正方形，上面的 顶部导航栏颜色过深 
> 华为 h30-u10, miui 8

**Comment by houyidg** [comment]
close

**Comment by isaak-zmg** [comment]
效果图圆角未实现 @zhuxiaogit @qaqaqa
