### ISSUE TITLE
界面显示异常

### ISSUE THREAD

**Issue by ffantasy** [SparxoOpenSource/Glood-ReactNative#44]
横条超出界面。
![screenshot_2016-12-23-12-02-10](https://cloud.githubusercontent.com/assets/8076045/21446996/cbef3f00-c908-11e6-8b38-9af1a6944497.jpg)

**Comment by houyidg** [comment]
close

**Comment by isaak-zmg** [comment]
消息样式 无论时间长短 都应显示为圆形 参照ios
