### ISSUE TITLE
房间中消息内容高度需自适应

### ISSUE THREAD

**Issue by isaak-zmg** [SparxoOpenSource/Glood-ReactNative#70]
![image](https://cloud.githubusercontent.com/assets/15681939/23327278/3d99c968-fabe-11e6-8c5a-a763929ade48.png)
可以参考IOS做法 每页固顶多少个 根据显示屏不同大小 动态调整

**Comment by Caskia** [comment]
参考ios计算内容高度

**Comment by Caskia** [comment]
姓名格式：lastname F.
