### ISSUE TITLE
返回菜单界面异常

### ISSUE THREAD

**Issue by Caskia** [SparxoOpenSource/Glood-ReactNative#75]
快速点击菜单两次，出现界面重叠

**Comment by qaqaqa** [comment]
@isaak-zmg 已解决，并且解决了以下问题，1.左边菜单栏按钮不易选中的问题 2.活动列表页面，点击顶部标题出收起活动列表页面的问题 3.活动卡片页面，快速点击顶部“communities”处，弹出两个活动列表页面
